name: Update Recent Repos

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README with recent repositories
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          feed_list: "https://github.com/KhalilNiazi" # Required by the action
          custom_post_type: "recent-repos"
          repo_type: "public"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
